### ISSUE TITLE
$(CLAGS) is missing in Makefile

### ISSUE THREAD

**Issue by pateretou** [rakhack/pwnpr#1]
Hello

please change 

```
# Default build
build:
        $(CXX) $(SOURCES) -o $(OUT) $(INCLUDES) $(LINKER_OPTIONS) $(LIBRARIES)
```

to

```
# Default build
build:
        $(CXX) $(SOURCES) -o $(OUT) $(CFLAGS) $(INCLUDES) $(LINKER_OPTIONS) $(LIBRARIES)

```

in the Makefile to compile :)

(or it won't compile on debian like system)

**Comment by rakhack** [comment]
@pateretou Thx, will do. Was rewriting Makefile for release, seems like missed it. Will fix it with the soonest commit, together with 0.1.1 release.

**Comment by rakhack** [comment]
Somehow, it was successfully compiling without -std=c++11 flag in spite of using C++11 features. Still, fixed.
